---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argo-cd
  namespace: argocd
spec:
  interval: 1h0m0s
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argocd
spec:
  chart:
    spec:
      chart: argo-cd
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: argo-cd
      version: '>=2.0.0'
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: argo-cd
  targetNamespace: argocd
  upgrade:
    crds: CreateReplace