apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: folder-apps
spec:
  generators:
  - list:
      elements:
      - folder: cert-manager
  template:
    metadata:
      name: '{{.folder}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-repo.git
        targetRevision: HEAD
        path: '{{.folder}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.folder}}'