apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-apps
spec:
  generators:
  - list:
      elements:
      - folder: cert-manager
  template:
    metadata:
      name: '{{.folder}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:UriZafrir/fluxcd-cluster.git
        targetRevision: HEAD
        path: '/clusters/cluster-1/argo/{{.folder}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.folder}}'